apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo-db
  name: mongo-db
spec:
  ports:
  - name: 27017-27017
    port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30017
  selector:
    app: mongo-db
  type: NodePort
status:
  loadBalancer: {}
